name: FakeMessage

main: com.niccholaspage.FakeMessage.FakeMessage

version: 0.5.2

commands:
  fsay:
    description: Fakes a chat message
    usage: /<command> name message
  fjoin:
    description: Fakes a join message
    usage: /<command> name
    aliases: fj
  fleave:
    description: Fakes a leave message
    usage: /<command> name
    aliases: fl
  fmsg:
    description: Fakes a personal message
    usage: /<command> toplayer name message
  fswitch:
    description: 
    usage: /<command> name